name: New Project
description: Create a new project for our SDK teams.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what should be delivered by this project.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why should we be doing this?
      description: If it is unclear why this is of importance, this ask might not be prioritized to your liking. Be specific about the goal, that you are trying to achieve. Tell us about the big picture and provide us with as much context as you can.
    validations:
      required: true
  - type: textarea
    id: why-now
    attributes:
      label: Why now?
      description: Please clarify why this came up just now. Be as specific as possible and also outline dependencies and timelines that you can share with us. 
    validations:
      required: true
  - type: input
    id: rfc
    attributes:
      label: RFC
      description: Is there already an RFC for this?
      placeholder: https://github.com/getsentry/rfcs/...
    validations:
      required: false
  - type: input
    id: slack-channel
    attributes:
      label: Slack-Channel
      description: Where is this project being discussed in Slack?
      placeholder: "#proj-my-new-project"
    validations:
      required: false
  - type: textarea
    id: notion
    attributes:
      label: Notion Document(s)
      description: Does any other documentation already exist?
      placeholder: Please add links to relevant Notion pages
    validations:
      required: false
  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholder(s)
      description: Please let us know who has an interest in this project.
    validations:
      required: false
  - type: textarea
    id: teams
    attributes:
      label: Team(s)
      description: Which teams will have to contribute to this project?
      placeholder: Mobile, Web Backend, Web Frontend
    validations:
      required: false
  - type: textarea
    id: sdks
    attributes:
      label: SDKs
      value: |
          ```[tasklist]
          ## SDKs
          - [ ] JavaScript SDK
          - [ ] Python SDK
          - [ ] PHP SDK
          - [ ] Laravel SDK
          - [ ] Symfony SDK
          - [ ] Go SDK
          - [ ] Ruby SDK
          - [ ] Elixir SDK
          - [ ] Rust SDK
          - [ ] Java SDK
          - [ ] .NET SDK
          - [ ] Unity SDK
          - [ ] Unreal SDK
          - [ ] PowerShell SDK
          - [ ] Android SDK
          - [ ] Apple/Cocoa SDK
          - [ ] Capacitor SDK
          - [ ] Cordova SDK
          - [ ] Dart SDK
          - [ ] Flutter SDK
          - [ ] Kotlin Multiplatform SDK
          - [ ] React Native SDK
          - [ ] Native SDK
          - [ ] Sentry CLI
          ```
  - type: markdown
    attributes:
      value: |-
        #### Next Steps
        After submitting this issue, your project will appear on our [project overview board](https://github.com/orgs/getsentry/projects/114) and a director will need to prioritize it.
